import { app, BrowserWindow, session } from 'electron';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 900,
    width: 1440,
    // titleBarStyle: 'hiddenInset',  // Makes title bar blend with the app
    // backgroundColor: '#ffffff',     // Match your app's background
    // trafficLightPosition: { x: 20, y: 20 },
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: true,
    },
  });

  // Set up CSP
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self' 'unsafe-inline' data:;" +
          "connect-src 'self' https://api.anthropic.com data:;" +
          "script-src 'self' 'unsafe-eval' 'unsafe-inline' data:;" +
          "style-src 'self' 'unsafe-inline' data:;"
        ]
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Initialize MCP service
import { initializeMCP } from './main/mcp';

// TODO: Make this configurable
const CMD = 'uv';
const ARGS = ['--directory', '/Users/artemm/Code/hide-mcp', 'run', 'hide-mcp', 'server'];
app.whenReady().then(() => {
  initializeMCP(CMD, ARGS).catch(err => {
    console.error('Failed to initialize MCP:', err);
  });
});
