import { app, BrowserWindow, ipcMain, session, dialog } from 'electron';
import * as path from 'path';
import * as fs from 'fs';

import { initializeDatabase, setupDbHandlers } from './main/db';
import { initializeMCP, listTools } from './main/mcp';
import { ChatService, setupChatHandlers } from './main/services/chat';
import { AnthropicService } from './main/services/anthropic';
import { captureEvent } from './lib/analytics/main';


// Store chat service reference for cleanup
let chatService: ChatService | null = null;

// Set up logging
const setupLogging = (debug: boolean = false) => {
  const logPath = path.join(app.getPath('userData'), 'logs');
  if (!fs.existsSync(logPath)) {
    fs.mkdirSync(logPath, { recursive: true });
  }

  const logFile = path.join(logPath, `${new Date().toISOString().split('T')[0]}.log`);
  const logStream = fs.createWriteStream(logFile, { flags: 'a' });

  // Redirect console.log and console.error to file
  const originalLog = console.log;
  const originalError = console.error;
  const originalDebug = console.debug;

  console.log = (...args) => {
    const message = args.map(arg =>
      typeof arg === 'object' ? JSON.stringify(arg, null, 2) : arg
    ).join(' ');
    logStream.write(`[LOG ${new Date().toISOString()}] ${message}\n`);
    originalLog.apply(console, args);
  };

  console.error = (...args) => {
    const message = args.map(arg =>
      typeof arg === 'object' ? JSON.stringify(arg, null, 2) : arg
    ).join(' ');
    logStream.write(`[ERROR ${new Date().toISOString()}] ${message}\n`);
    originalError.apply(console, args);
  };

  console.debug = (...args) => {
    if (debug) {
      const message = args.map(arg =>
        typeof arg === 'object' ? JSON.stringify(arg, null, 2) : arg
      ).join(' ');
      logStream.write(`[DEBUG ${new Date().toISOString()}] ${message}\n`);
      originalDebug.apply(console, args);
    };
  }

  // Log startup info
  console.debug('App starting...', {
    version: app.getVersion(),
    electron: process.versions.electron,
    chrome: process.versions.chrome,
    node: process.versions.node,
    platform: process.platform,
    arch: process.arch,
    isPackaged: app.isPackaged,
    resourcesPath: process.resourcesPath,
    appPath: app.getAppPath(),
    userData: app.getPath('userData')
  });
};
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Set up logging as early as possible
const DEBUG = process.env.HIDE_APP_DEBUG === 'true';
setupLogging(DEBUG);

// Catch any uncaught errors
process.on('uncaughtException', (error) => {
  captureEvent('uncaught_exception', {
    error: error.toString(),
    stack: error.stack,
    details: error
  });
  console.error('Uncaught exception:', {
    error: error.toString(),
    stack: error.stack,
    details: error
  });
});

process.on('unhandledRejection', (reason, _promise) => {
  const error = reason instanceof Error ? reason : new Error(String(reason));
  captureEvent('unhandled_rejection', {
    error: error.toString(),
    stack: error.stack,
    details: reason
  });
  console.error('Unhandled rejection:', {
    error: error.toString(),
    stack: error.stack,
    details: reason
  });
});

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 900,
    width: 1440,
    titleBarStyle: 'hidden',
    backgroundColor: 'rgb(2 6 23)', // This should match your sidebar dark background
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: true,
      nodeIntegration: false,
      contextIsolation: true
    },
  });

  // Set CSP headers
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self';",
          "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://eu-assets.i.posthog.com;",
          "style-src 'self' 'unsafe-inline' data:;",
          "connect-src 'self' https://eu.i.posthog.com https://eu-assets.i.posthog.com https://api.anthropic.com;",
          "img-src 'self' data: https:;",
        ].join(' ')
      }
    });
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
  return mainWindow;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('will-quit', async () => {
  if (chatService) {
    console.debug('Stopping all active chats before quit...');
    try {
      await chatService.stopAllChats();
      console.debug('All chats stopped successfully');
    } catch (error) {
      captureEvent('error_stopping_chats', {
        error: error.toString()
      });
      console.error('Error stopping chats:', error);
    }
  }
  captureEvent('app_quit');
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

const getMCPConfig = async () => {
  const mcpPath = !app.isPackaged
    ? process.env.LOCAL_MCP_PATH  // Development TODO: Make this configurable
    : path.join(process.resourcesPath, 'hide-mcp');  // Production (binary)

  // Log some diagnostic information
  console.debug('MCP configuration:', {
    production: app.isPackaged,
    resourcesPath: process.resourcesPath,
    mcpPath,
    exists: fs.existsSync(mcpPath),
  });

  // Verify that MCP exists
  if (!fs.existsSync(mcpPath)) {
    captureEvent('mcp_not_found', {
      error: `MCP not found at ${mcpPath}`
    });
    throw new Error(`MCP not found at ${mcpPath}`);;
  }

  // In development, use system's uv
  if (!app.isPackaged) {
    return {
      cmd: 'uv',
      args: ['--directory', mcpPath, 'run', 'hide-mcp', 'server']
    };
  }

  // In production, use binary
  return {
    cmd: mcpPath,
    args: [
      'server'
    ]
  };
};

// Handle directory picker dialog
ipcMain.handle('dialog:showDirectoryPicker', async () => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory', 'createDirectory'],
    title: 'Select Project Directory',
  });
  return result;
});

app.whenReady().then(async () => {
  // Track app initialization
  captureEvent('app_initialized', {
    is_packaged: app.isPackaged,
    debug_mode: DEBUG
  });

  // Initialize the database and set up IPC handlers
  initializeDatabase();
  setupDbHandlers();

  const { cmd, args } = await getMCPConfig();
  console.debug('Initializing MCP...', { cmd, args });

  try {
    // Initialize MCP first
    const initPromise = initializeMCP(cmd, args);

    // Create window immediately but don't wait for services
    const mainWindow = createWindow();

    // Wait for MCP initialization
    await initPromise;
    console.debug('MCP initialized successfully');

    // Now that MCP is ready, initialize Anthropic service
    const tools = await listTools();
    const anthropicService = new AnthropicService(tools);

    // Create chat service
    chatService = new ChatService(anthropicService);
    setupChatHandlers(chatService);

    const settingsStatus = anthropicService.loadSettings();
    if (!settingsStatus.success) {
      console.debug('Credentials missing, notifying renderer process:', settingsStatus.error);
      captureEvent('credentials_missing', {
        error: settingsStatus.error
      });
      mainWindow.webContents.send('credentials:required', settingsStatus.error);
    }
    console.debug('chat service initialized successfully');
  } catch (err) {
    captureEvent('initialization_error', {
      error_type: err.name,
      error_message: err.message
    });
    console.error('Failed to initialize application:', err);
    // Show an error dialog to the user
    dialog.showErrorBox(
      'Error Starting Application',
      `Failed to initialize required services. Error: ${err.message}. The application may not work correctly.`
    );
  }
});
